[package]
name = "tests"
version = "0.1.0"
edition = "2024"

[dependencies]
boxer-issuer-http = { path = "../boxer-issuer-http" }
boxer_core = { path = "../../../boxer-core/" }
#boxer_core = { git = "https://github.com/SneaksAndData/boxer-core.git", tag = "v0.0.26" }
actix-web = "4.14.0"
tokio = "1.52.3"
anyhow = "1.0.103"
mockall = "0.14.0"
async-trait = "0.1.81"
cedar-policy = "4.4.0"
reqwest = { version = "0.13.4", features = ["form"] }
rustls = "0.23.41"
serde_json = "1.0.150"
env_filter = "0.1.3"
env_logger = "0.11.5"
log = "0.4.33"
